default:
  driver: ODBC Driver 18 for SQL Server
  log_level: DEBUG
  redirect: http://localhost:3838

connect_cloud:
  driver: SQLServer
  log_level: DEBUG
  redirect: https://rilevazioniupipa-timbrature2.share.connect.posit.cloud